[package]
name = "core"
version = "2.0.0"
authors = ["Shunquan Wang <shunqwang@gmail.com>"]
description = "The application core code"
edition = "2021"

[dependencies]
utils = { path = "../utils" }

rand = "0.8.5"
log = "0.4.20"
