[package]
name = "utils"
version = "2.0.0"
authors = ["Shunquan Wang <shunqwang@gmail.com>"]
description = "Various utilities and functionalities"
edition = "2021"

[features]
nightly = []
termlog = []
syslog = []
journald = []

[dependencies]
thiserror = "1.0.63"
backtrace = "0.3.73"
color-backtrace = "0.6.1"
config = "0.14.0"
lazy_static = "1.5.0"
slog = "2.7.0"
slog-syslog = "0.13.0"
slog-term = "2.9.1"
slog-scope = "4.4.0"
slog-async = "2.8.0"
slog-stdlog = "4.1.1"
serde = "1.0.210"
clap = "4.5.20"
log = "0.4.22"
[target.'cfg(target_os = "linux")'.dependencies]
slog-journald = "2.2.0"
log = "0.4.22"

